### PR TITLE
New Website Design?

### PR DESCRIPTION
**Pull request by AstroNode**
I was bored one day and saw that the PrismarineJS project's website needed a bit of a facelift, so I got to work on updating the design, minifying the code, optimizing SEO, etc. I also compiled Bootstrap v4 Alpha myself and applied it to the repo.

The website _should_ look better and load a little bit faster now.

### CODE REVIEW

**Comment by rom1504** [comment]
Can you put it also on your gh-pages branch so we can see how it looks like ?

**Comment by rom1504** [comment]
Ah nevermind, it's there I guess http://astronode.github.io/

**Comment by AstroNode** [comment]
If there's any issues with it, I'll be able to deal with it. Just wanted to spice up your project's presentation :P

**Comment by BradyLF** [comment]
Loved it, merged the pull

**Comment by rom1504** [comment]
I'm not that much convinced that this design is better, but I don't really care.
There is a problem though: there were 9 names, now there is 5, can you add back the 4 you removed ?

**Comment by dcbartlett** [comment]
While you're at it, BradyLF is in charge of marketing and if he'd like i'm ok with adding you to the web team.

**Comment by BradyLF** [comment]
Sounds good to me!

**Comment by dcbartlett** [comment]
@AstroNode what you say?

**Comment by AstroNode** [comment]
@dcbartlett :+1:

**Comment by dcbartlett** [comment]
@AstroNode please submit a code update to add yourself to the list under brady, i'll go ahead and add you to git permissions so you can push directly.

**Comment by AstroNode** [comment]
@dcbartlett Done.

**Comment by dcbartlett** [comment]
did you push? i don't see you on the site.  You should be able to push directly now without needing a PR.

**Comment by AstroNode** [comment]
Didn't seem to work

**Comment by dcbartlett** [comment]
Ah, sorry, you have to accept the invite to become part of the team, then you can push.

https://github.com/PrismarineJS

**Comment by AstroNode** [comment]
Thanks!

**Pull request merged**
